### ISSUE TITLE
Server-side errors when re-running a new protocol on all models

### ISSUE THREAD

**Issue by mirams** [ModellingWebLab/deployment#24]
I got this error when re-running all experiments with a new version of a protocol on scrambler

![image](https://user-images.githubusercontent.com/858776/68941247-33e30f80-079d-11ea-9a4d-9d259ea31398.png)

@jonc125 saw  `504 Gateway Time-out` in the server logs:
> "Seems the back-end CGI gets overwhelmed with too many requests at once so doesn't respond to them all in time"

**Comment by jonc125** [comment]
See also https://rollbar.com/jonc125/Web-Lab/items/66/

**Comment by mirams** [comment]
At least one of the two that failed here happens to be on the "All visible" but not the "Moderated" default page of experiments, not sure whether that is a clue or red herring!

**Comment by jonc125** [comment]
It'll be random which fail, depending on the order things are submitted and when it runs out of workers.
